# 🧠 Manhwa Recommendation System - Final Version

Notebook ini mencakup seluruh proses pembuatan sistem rekomendasi manhwa dengan dua fitur utama:
1. Rekomendasi berdasarkan judul
2. Rekomendasi berdasarkan keyword bebas

Selain itu, notebook ini juga menggabungkan cover manhwa dari API AniList dan menyimpan hasilnya ke berbagai format (pickle dan Excel).

In [1]:
import pandas as pd
import requests
import numpy as np
import nltk
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import pickle
import gzip
#!pip install googletrans
from googletrans import Translator
# Download stopwords for English
# nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Load Dataset

In [2]:
# Load Dataset
df = pd.read_excel('Manhwa_Dataset.xlsx')
df

,no,type,title,chapters,status,genres,favorites,popularity,rank,score,members,synopsis,volumns,authors,publish_time
0,0,manhwa,Solo Leveling,201,Finished,"Action,Adventure,Fantasy",40.014,#7,#56,8.68,431.289,"Ten years ago, ""the Gate"" appeared and connect...",Unknown,"Chugong (Story), Jang, Sung-rak (Art), Discipl...","Mar 4, 2018 to May 31, 2023"
1,1,manhwa,The Horizon,21,Finished,"Adventure,Drama",4.047,#187,#58,8.67,75.806,"In a world ravaged by war, a young boy walks d...",3,"Jeong, Ji-Hoon (Story & Art)","Mar 30, 2016 to Jul 21, 2016"
2,2,manhwa,Wind Breaker,Unknown,Publishing,"Action,Drama,Sports",2.688,#368,#94,8.58,42.434,"Burdened with expectations since childhood, se...",Unknown,"Jo, Yongseok (Story & Art)","Dec 15, 2013 to ?"
3,3,manhwa,Bastard,94,Finished,"Drama,Horror,Mystery,Romance",6.455,#84,#140,2024-05-08 00:00:00,126.088,There is nowhere that Seon Jin can find solace...,5,"Kim, Carnby (Story), Hwang, Young-chan (Art)","Jul 4, 2014 to May 6, 2016"
4,4,manhwa,Who Made Me a Princess,125,Finished,"Comedy,Fantasy,Romance",2.648,#349,#175,8.44,44.428,"In the novel The Lovely Princess, the secondar...",9,"Plutus (Story), Spoon (Art)","Dec 20, 2017 to Apr 30, 2022"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2938,2938,manhwa,Lessons in Lust,41,Finished,"Love,Erotica",0.000,#36574,NaN,NaN,137.000,"Ivan is a guardian android, responsible for te...",Unknown,"Akkang (Story), Wabec (Art)","May 17, 2020 to Feb 6, 2021"
2939,2939,manhwa,Cradle of Imae,64,Finished,"Love,Fantasy,Erotica",1.000,#25482,NaN,NaN,332.000,"In the demon-plagued kingdom of Jinyeok, a chi...",Unknown,"Mum (Story & Art), Rayuan (Story & Art)","Oct 30, 2019 to May 5, 2021"
2940,2940,manhwa,The Desire to Kill,37,Finished,Erotica,2.000,#30410,NaN,NaN,218.000,Every man wants Si-ae. Her voluptuous figure a...,Unknown,ButcherBoy (Story & Art),"Apr 30, 2019 to May 10, 2020"
2941,2941,manhwa,Bad Boy,40,Finished,"Love,Drama,Erotica",1.000,#45336,NaN,NaN,77.000,One of the professors found out that a student...,6,"Lee, Hyeon-Sook (Story & Art)","Aug 1, 2014 to Apr 11, 2016"
2942,2942,manhwa,Core Scramble,24,Finished,"Action,Love,Comedy,Drama,Sci-Fi,Erotica",4.000,#33096,NaN,NaN,177.000,In a world plagued by monsters swarming throug...,3,"Jun, Euho (Story & Art)",Jun 2011 to Nov 2011

# Preprocessing Function

In [3]:
# no, title, genres, synopsis, authors

df = df[['no','title','synopsis','genres','authors','score']]

In [4]:
df.head(5)

,no,title,synopsis,genres,authors,score
0,0,Solo Leveling,"Ten years ago, ""the Gate"" appeared and connect...","Action,Adventure,Fantasy","Chugong (Story), Jang, Sung-rak (Art), Discipl...",8.68
1,1,The Horizon,"In a world ravaged by war, a young boy walks d...","Adventure,Drama","Jeong, Ji-Hoon (Story & Art)",8.67
2,2,Wind Breaker,"Burdened with expectations since childhood, se...","Action,Drama,Sports","Jo, Yongseok (Story & Art)",8.58
3,3,Bastard,There is nowhere that Seon Jin can find solace...,"Drama,Horror,Mystery,Romance","Kim, Carnby (Story), Hwang, Young-chan (Art)",2024-05-08 00:00:00
4,4,Who Made Me a Princess,"In the novel The Lovely Princess, the secondar...","Comedy,Fantasy,Romance","Plutus (Story), Spoon (Art)",8.44

In [5]:
df.isnull().sum()

no             0
title          0
synopsis     155
genres         0
authors       57
score       1446
dtype: int64

In [6]:
# Step 1: Ubah nilai non-float ATAU NaN pada kolom 'score'
def is_invalid_score(val):
    try:
        if pd.isna(val):  # jika NaN
            return True
        float(val)        # coba konversi ke float
        return False
    except (ValueError, TypeError):
        return True

# Terapkan ke kolom 'score' dengan .loc agar bebas dari warning
df.loc[:, 'score'] = df['score'].apply(lambda x: 'Data Rating tidak Tersedia' if is_invalid_score(x) else float(x))

In [7]:
df.head(5)

,no,title,synopsis,genres,authors,score
0,0,Solo Leveling,"Ten years ago, ""the Gate"" appeared and connect...","Action,Adventure,Fantasy","Chugong (Story), Jang, Sung-rak (Art), Discipl...",8.68
1,1,The Horizon,"In a world ravaged by war, a young boy walks d...","Adventure,Drama","Jeong, Ji-Hoon (Story & Art)",8.67
2,2,Wind Breaker,"Burdened with expectations since childhood, se...","Action,Drama,Sports","Jo, Yongseok (Story & Art)",8.58
3,3,Bastard,There is nowhere that Seon Jin can find solace...,"Drama,Horror,Mystery,Romance","Kim, Carnby (Story), Hwang, Young-chan (Art)",Data Rating tidak Tersedia
4,4,Who Made Me a Princess,"In the novel The Lovely Princess, the secondar...","Comedy,Fantasy,Romance","Plutus (Story), Spoon (Art)",8.44

In [8]:
df.isnull().sum()

no            0
title         0
synopsis    155
genres        0
authors      57
score         0
dtype: int64

In [9]:
# Step 2: Drop baris yang NaN tapi tidak termasuk kolom 'score'
df = df.dropna(subset=['title', 'synopsis', 'genres', 'authors'])  # jangan include 'score' di sini

In [10]:
df.isnull().sum()

no          0
title       0
synopsis    0
genres      0
authors     0
score       0
dtype: int64

In [11]:
df = df[~df['genres'].str.contains('erotica', case=False, na=False)]

In [12]:
print(df['genres'].str.contains('erotica', case=False).any())
# Output harusnya False

False

In [13]:
df.shape

(2427, 6)

In [14]:
df

,no,title,synopsis,genres,authors,score
0,0,Solo Leveling,"Ten years ago, ""the Gate"" appeared and connect...","Action,Adventure,Fantasy","Chugong (Story), Jang, Sung-rak (Art), Discipl...",8.68
1,1,The Horizon,"In a world ravaged by war, a young boy walks d...","Adventure,Drama","Jeong, Ji-Hoon (Story & Art)",8.67
2,2,Wind Breaker,"Burdened with expectations since childhood, se...","Action,Drama,Sports","Jo, Yongseok (Story & Art)",8.58
3,3,Bastard,There is nowhere that Seon Jin can find solace...,"Drama,Horror,Mystery,Romance","Kim, Carnby (Story), Hwang, Young-chan (Art)",Data Rating tidak Tersedia
4,4,Who Made Me a Princess,"In the novel The Lovely Princess, the secondar...","Comedy,Fantasy,Romance","Plutus (Story), Spoon (Art)",8.44
...,...,...,...,...,...,...
2605,2605,Sherlock,The story of the famous Sherlock Holmes revisi...,Mystery,"Kwon, Gyo-jung (Story & Art)",Data Rating tidak Tersedia
2606,2606,Trap,He gets trapped due to his sexuality.\n\nA man...,"Love,Drama","Min, Song-A (Story & Art)",Data Rating tidak Tersedia
2607,2607,[Un]hero,The Damned Devil's Army are rampaging around t...,"Fantasy,Sci-Fi","Kim, Jae-Hwan (Story & Art), Jo, Seung-Yeop (S...",Data Rating tidak Tersedia
2608,2608,Papaya,"The girl with psychic abilities Sae-in, the pr...","Romance,Supernatural","Kang, Eun Young (Story & Art)",Data Rating tidak Tersedia
2609,2609,Zero Taker,A terrible virus turning its victims into bloo...,"Action,Sci-Fi","Choi, Yoon Yeol (Art), Kim, Goon (Story)",Data Rating tidak Tersedia

In [15]:
df = df.reset_index(drop=True)
df

,no,title,synopsis,genres,authors,score
0,0,Solo Leveling,"Ten years ago, ""the Gate"" appeared and connect...","Action,Adventure,Fantasy","Chugong (Story), Jang, Sung-rak (Art), Discipl...",8.68
1,1,The Horizon,"In a world ravaged by war, a young boy walks d...","Adventure,Drama","Jeong, Ji-Hoon (Story & Art)",8.67
2,2,Wind Breaker,"Burdened with expectations since childhood, se...","Action,Drama,Sports","Jo, Yongseok (Story & Art)",8.58
3,3,Bastard,There is nowhere that Seon Jin can find solace...,"Drama,Horror,Mystery,Romance","Kim, Carnby (Story), Hwang, Young-chan (Art)",Data Rating tidak Tersedia
4,4,Who Made Me a Princess,"In the novel The Lovely Princess, the secondar...","Comedy,Fantasy,Romance","Plutus (Story), Spoon (Art)",8.44
...,...,...,...,...,...,...
2422,2605,Sherlock,The story of the famous Sherlock Holmes revisi...,Mystery,"Kwon, Gyo-jung (Story & Art)",Data Rating tidak Tersedia
2423,2606,Trap,He gets trapped due to his sexuality.\n\nA man...,"Love,Drama","Min, Song-A (Story & Art)",Data Rating tidak Tersedia
2424,2607,[Un]hero,The Damned Devil's Army are rampaging around t...,"Fantasy,Sci-Fi","Kim, Jae-Hwan (Story & Art), Jo, Seung-Yeop (S...",Data Rating tidak Tersedia
2425,2608,Papaya,"The girl with psychic abilities Sae-in, the pr...","Romance,Supernatural","Kang, Eun Young (Story & Art)",Data Rating tidak Tersedia
2426,2609,Zero Taker,A terrible virus turning its victims into bloo...,"Action,Sci-Fi","Choi, Yoon Yeol (Art), Kim, Goon (Story)",Data Rating tidak Tersedia

In [16]:
df.shape

(2427, 6)

In [17]:
# Inisialisasi stemmer
ps = PorterStemmer()

# Preprocessing Function
def clean_text(text):
    if pd.isna(text):
        return ""
    
    # Case folding
    text = str(text).lower()
    
    # Filtering: remove non-alphanumeric characters
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    
    # Tokenizing
    tokens = text.split()
    
    # Stopword removal
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    
    # Stemming
    tokens = [ps.stem(word) for word in tokens]
    
    return ' '.join(tokens)

# Apply to necessary columns
df['clean_title'] = df['title'].apply(clean_text)
df['clean_synopsis'] = df['synopsis'].apply(clean_text)
df['clean_genres'] = df['genres'].apply(clean_text)
df['clean_authors'] = df['authors'].apply(clean_text)

# Combine Tags
df['tags'] = (
    (df['clean_title'] + ' ') * 3 +
    (df['clean_genres'] + ' ') * 4 +
    (df['clean_authors'] + ' ') * 2 +
    df['clean_synopsis']
)

## 📥 Load Cover from API AniList

In [29]:
import requests
import time

# Fungsi ambil cover dari Anilist
def get_cover_url(title, cache={}):
    if title in cache:
        return cache[title]
    
    url = 'https://graphql.anilist.co'
    query = '''
    query ($search: String) {
      Media(search: $search, type: MANGA) {
        coverImage {
          large
        }
      }
    }
    '''
    variables = {'search': title}
    
    try:
        response = requests.post(url, json={'query': query, 'variables': variables})
        response.raise_for_status()
        data = response.json()
        cover = data['data']['Media']['coverImage']['large']
        cache[title] = cover
        return cover
    except:
        return 'https://via.placeholder.com/150?text=No+Image'

# --- PROSES PERTAMA: ambil cover dari Anilist ---

# Tambahkan delay untuk menghindari rate limit Anilist (misal 1 detik per request)
print("Memulai proses ambil cover dari Anilist...")
start_time = time.time()

cover_list = []
for idx, row in df.iterrows():
    title = row['title']
    cover = get_cover_url(title)
    cover_list.append(cover)
    time.sleep(1)  # delay 1 detik

df['cover_url'] = cover_list

end_time = time.time()
elapsed_time = end_time - start_time
print(f"Proses selesai. Waktu yang dibutuhkan: {elapsed_time/60:.2f} menit")

Memulai proses ambil cover dari Anilist...
Proses selesai. Waktu yang dibutuhkan: 101.88 menit

## 📥 Load Cover from MAL (Jikan API)

In [30]:
# Fungsi ambil cover dari MAL
def fetch_mal_cover(title):
    try:
        response = requests.get(f"https://api.jikan.moe/v4/manga?q={title}&type=manhwa")
        response.raise_for_status()
        data = response.json()
        if data['data']:
            return data['data'][0]['images']['jpg']['large_image_url']
    except:
        pass
    return None

# --- PROSES KEDUA: melengkapi cover dengan MAL untuk yang masih placeholder ---

print("Memulai proses melengkapi cover dengan MAL...")
start_time = time.time()

fixed_cover_list = []
for idx, row in df.iterrows():
    current_cover = row['cover_url']
    title = row['title']
    
    if 'via.placeholder.com' in current_cover:
        mal_cover = fetch_mal_cover(title)
        if mal_cover:
            fixed_cover_list.append(mal_cover)
        else:
            fixed_cover_list.append(current_cover)  # tetap pakai placeholder
        time.sleep(1.2)  # delay 1.2 detik untuk Jikan API
    else:
        fixed_cover_list.append(current_cover)

df['cover_url'] = fixed_cover_list

end_time = time.time()
elapsed_time = end_time - start_time
print(f"Proses selesai. Waktu yang dibutuhkan: {elapsed_time/60:.2f} menit")

Memulai proses melengkapi cover dengan MAL...
Proses selesai. Waktu yang dibutuhkan: 2.42 menit

In [31]:
df.isnull().sum()

no                0
title             0
synopsis          0
genres            0
authors           0
score             0
clean_title       0
clean_synopsis    0
clean_genres      0
clean_authors     0
tags              0
cover_url         0
dtype: int64

In [32]:
df.shape

(2427, 12)

In [33]:
df.shape

(2427, 12)

In [40]:
df

,no,title,synopsis,genres,authors,score,clean_title,clean_synopsis,clean_genres,clean_authors,tags,cover_url
0,0,Solo Leveling,"Ten years ago, ""the Gate"" appeared and connect...","Action,Adventure,Fantasy","Chugong (Story), Jang, Sung-rak (Art), Discipl...",8.68,solo level,ten year ago gate appear connect real world re...,actionadventurefantasi,chugong stori jang sungrak art discipl art,solo level solo level solo level actionadventu...,https://s4.anilist.co/file/anilistcdn/media/ma...
1,1,The Horizon,"In a world ravaged by war, a young boy walks d...","Adventure,Drama","Jeong, Ji-Hoon (Story & Art)",8.67,horizon,world ravag war young boy walk lone road after...,adventuredrama,jeong jihoon stori art,horizon horizon horizon adventuredrama adventu...,https://s4.anilist.co/file/anilistcdn/media/ma...
2,2,Wind Breaker,"Burdened with expectations since childhood, se...","Action,Drama,Sports","Jo, Yongseok (Story & Art)",8.58,wind breaker,burden expect sinc childhood secondyear high s...,actiondramasport,jo yongseok stori art,wind breaker wind breaker wind breaker actiond...,https://s4.anilist.co/file/anilistcdn/media/ma...
3,3,Bastard,There is nowhere that Seon Jin can find solace...,"Drama,Horror,Mystery,Romance","Kim, Carnby (Story), Hwang, Young-chan (Art)",Data Rating tidak Tersedia,bastard,nowher seon jin find solac school ruthlessli b...,dramahorrormysteryrom,kim carnbi stori hwang youngchan art,bastard bastard bastard dramahorrormysteryrom ...,https://s4.anilist.co/file/anilistcdn/media/ma...
4,4,Who Made Me a Princess,"In the novel The Lovely Princess, the secondar...","Comedy,Fantasy,Romance","Plutus (Story), Spoon (Art)",8.44,made princess,novel love princess secondari charact athanasi...,comedyfantasyrom,plutu stori spoon art,made princess made princess made princess come...,https://s4.anilist.co/file/anilistcdn/media/ma...
...,...,...,...,...,...,...,...,...,...,...,...,...
2422,2605,Sherlock,The story of the famous Sherlock Holmes revisi...,Mystery,"Kwon, Gyo-jung (Story & Art)",Data Rating tidak Tersedia,sherlock,stori famou sherlock holm revisit kwon gyojung,mysteri,kwon gyojung stori art,sherlock sherlock sherlock mysteri mysteri mys...,https://s4.anilist.co/file/anilistcdn/media/ma...
2423,2606,Trap,He gets trapped due to his sexuality.\n\nA man...,"Love,Drama","Min, Song-A (Story & Art)",Data Rating tidak Tersedia,trap,get trap due sexual man break male longterm lo...,lovedrama,min songa stori art,trap trap trap lovedrama lovedrama lovedrama l...,https://s4.anilist.co/file/anilistcdn/media/ma...
2424,2607,[Un]hero,The Damned Devil's Army are rampaging around t...,"Fantasy,Sci-Fi","Kim, Jae-Hwan (Story & Art), Jo, Seung-Yeop (S...",Data Rating tidak Tersedia,unhero,damn devil armi rampag around world person sto...,fantasyscifi,kim jaehwan stori art jo seungyeop stori art,unhero unhero unhero fantasyscifi fantasyscifi...,https://s4.anilist.co/file/anilistcdn/media/ma...
2425,2608,Papaya,"The girl with psychic abilities Sae-in, the pr...","Romance,Supernatural","Kang, Eun Young (Story & Art)",Data Rating tidak Tersedia,papaya,girl psychic abil saein pretti foreign boy har...,romancesupernatur,kang eun young stori art,papaya papaya papaya romancesupernatur romance...,https://s4.anilist.co/file/anilistcdn/media/ma...
2426,2609,Zero Taker,A terrible virus turning its victims into bloo...,"Action,Sci-Fi","Choi, Yoon Yeol (Art), Kim, Goon (Story)",Data Rating tidak Tersedia,zero taker,terribl viru turn victim bloodthirsti mutant t...,actionscifi,choi yoon yeol art kim goon stori,zero taker zero taker zero taker actionscifi a...,https://s4.anilist.co/file/anilistcdn/media/ma...

## 📐 TF-IDF Vectorizer & Similarity Calculation

In [34]:
# Custom vectorizer with stopwords, n-gram
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS

custom_stopwords = {'manhwa', 'read', 'chapter', 'series', 'story', 'sourc', 'art', 'stori'}
all_stopwords = list(ENGLISH_STOP_WORDS.union(custom_stopwords))

# Untuk rekomendasi by judul
vectorizer_title = TfidfVectorizer(
    stop_words=all_stopwords,
    ngram_range=(1, 2),
    token_pattern=r'\b\w+\b'
)
tag_matrix = vectorizer_title.fit_transform(df['tags'])
similarity = cosine_similarity(tag_matrix)

# Untuk rekomendasi by keyword
tag_vectorizer = TfidfVectorizer(
    stop_words=all_stopwords,
    ngram_range=(1, 2),
    token_pattern=r'\b\w+\b'
)
tag_vectors = tag_vectorizer.fit_transform(df['tags'])

In [35]:
similarity[0]

array([1.        , 0.01084363, 0.00665317, ..., 0.00260823, 0.        ,
       0.00236932])

## 💾 Simpan Dataset dan Model

In [36]:
# Save compressed pickle
with gzip.open('manhwa_dict_with_cover.pkl.gz', 'wb') as f:
    pickle.dump(df[['no', 'title', 'synopsis', 'genres', 'authors', 'score', 'tags', 'cover_url']].to_dict(), f)

with gzip.open('similarity.pkl.gz', 'wb') as f:
    pickle.dump(similarity, f)

with gzip.open('tag_vectorizer.pkl.gz', 'wb') as f:
    pickle.dump(tag_vectorizer, f)

with gzip.open('tag_vectors.pkl.gz', 'wb') as f:
    pickle.dump(tag_vectors, f)

print("✅ Semua file berhasil disimpan!")

✅ Semua file berhasil disimpan!

## Fitur Terjemahan

In [37]:
translator = Translator()

def translate_to_english(text):
    translated = translator.translate(text, src='id', dest='en')
    return translated.text

# Fungsi Rekomendasi Berdasarkan Judul

In [38]:
def recommend_by_title(selected_title):
    idx = df[df['title'] == selected_title].index[0]
    distances = similarity[idx]
    manhwa_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    
    results = []
    for i in manhwa_list:
        row = df.iloc[i[0]]
        results.append((row['title'], row['cover_url']))
    return results

# Fungsi Rekomendasi Berdasarkan Keyword

In [39]:
def recommend_by_keyword(user_input):
    # Translate user input to English if necessary
    if is_indonesian(user_input):
        user_input = translate_to_english(user_input)
    
    user_vec = tag_vectorizer.transform([user_input])
    scores = cosine_similarity(user_vec, tag_vectors).flatten()
    top_indices = scores.argsort()[::-1][:5]
    
    results = []